name: kmer2stats
owner: iuc
description: A tool for creating data files for statistic based on kmers
homepage_url: https://github.com/SantaMcCloud/kmer2stats
long_description: |
  This tool calculate diversity based on counted kmers.
  This tool was design to use the output from jellyfish 
  but it also can take a file in specific format.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/kmer2stats/
type: unrestricted
categories: 
- Metagenomics