categories:  # see https://toolshed.g2.bx.psu.edu/repository/browse_categories  
- Data Source
- Imaging
- File Formats
- Multimedia
- Quality Control
description: Tool to check multimedia files if they are corrupt or duplicated
long_description: |
    Do you have a huge number of multimedia files and you don't know if they are corrupt,
    or if they have the correct extension?
    This tool:

    - gives you an overview of what file types there are
    - checks if the extension of the files match their content
    - checks if there are any duplicates
    - checks if the content of the files is intact
homepage_url: https://github.com/dasch-swiss/fileidentification
name: fileidentification
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/fileidentification
type: unrestricted
maintainers:  # github usernames
- flo7ian
- jnussbaum
- subotic
