categories: [Data Source, Imaging]
description: Check multimedia files if they are corrupt or duplicated
homepage_url: https://github.com/dasch-swiss/fileidentification
name: fileidentification
owner: johannes_nussbaum
remote_repository_url: https://github.com/dasch-swiss/fileidentification-galaxy
