name: kmetashot
owner: iuc
description: an alignment-free taxonomic classifier based on k-mer/minimizer counting
long_description: |
  kMetaShot, a bioinformatic approach relying on k-mer/minimizer profiling 
  from the reference prokaryotic genomes, in order to build a concise 
  representation of genomic diversity and perform MAG taxonomic 
  classification up to the strain level
homepage_url: https://github.com/gdefazio/kMetaShot
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/kmetashot
categories:
  - Metagenomics
type: unrestricted