name: fastq_groupmerge
owner: iuc
description: A tool for merging sample reads by metadata
homepage_url: https://github.com/SantaMcCloud/fastq-groupmerge
long_description: |
  This tool take multiple sample reads as input which then can be merged in
  any possible way based on the inputted metadata file.
  It should help for workflows to run certain style of analysis like co-assemble or
  any other use case where merging reads is mandatory.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/fastq_groupmerge
type: unrestricted
categories: 
- Metagenomics