categories:
- Data Managers
- Metagenomics
homepage_url: https://github.com/gdefazio/kMetaShot
description: Data manager for kMetaShot reference data
long_description: Data manager for kMetaShot reference data
name: kmetashot_build_database
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_kmetashot
type: unrestricted